[tool.poetry]
name = "health-analysis"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "api", from="src"}]

[tool.poetry.dependencies]
python = "^3.12"
taskiq = "^0.11.6"
taskiq-aio-pika = "^0.4.0"
esdbclient = "^1.1"
mypy = "^1.11.1"
psycopg2 = "^2.9.9"
python-dotenv = "^1.0.1"
isort = "^5.13.2"
black = "^24.8.0"
pylint = "^3.2.6"
taskiq-redis = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
