[timescaledb]

    [timescaledb.credentials]
    # TEMPLATE: dsn="postgres://user:password@localhost:5433" 
    user="user"
    password="password"
    host="localhost"
    port="5433"

[eventstoredb]

    [eventstoredb.credentials]
    # TEMPLATE: uri="esdb://localhost:2113?tls=false"
    user="user"
    password="password"
    host="localhost"
    port="2113"
    tls="false"

    [eventstoredb.subscriptions]

        [eventstoredb.subscriptions.meals]
            stream="StreamMeals"
            from_end=true

        [eventstoredb.subscriptions.health]
            stream="StreamHealth"
            from_end=true

    [eventstoredb.events]

        [eventstoredb.events.meals]
            insert="InsertMeal"
            deletes="DeleteMeal"

        [eventstoredb.events.health]
            insert="InsertHealth"
            delete="DeleteHealth"


[rabbitmq]

    [rabbitmq.credentials]
    # TEMPLATE: url="amqp://guest:guest@localhost:5672"
    user="guest"
    password="guest"
    host="localhost"
    port="5672"

    [rabbitmq.queues]

        [rabbitmq.queues.meals]
        queue_name="meals.queue"

        [rabbitmq.queues.health]
        queue_name="meals.health"

    [rabbitmq.exchanges]

        [rabbitmq.exchanges.meals]
        exchange_name="meals.exchange"

        [rabbitmq.exchanges.health]
        exchange_name="health.exchange"


[logging]
version = 1

    [logging.formatters.formatter]
    format = "[%(asctime)s] [%(levelname)s] [%(filename)s:%(funcName)s:%(lineno)d]: %(message)s"

    [logging.handlers]
    
        [logging.handlers.console]
        class = "logging.StreamHandler"
        level = "DEBUG"
        formatter = "formatter"
        stream = "ext://sys.stderr"

    [logging.root]
    level = "DEBUG"
    handlers = ["console"]

