[dns]

    [dns.timescaledb]
    # TEMPLATE: dsn="postgres://user:password@localhost:5433" 
    user="user"
    password="password"
    host="localhost"
    port="5433"

    [dns.eventstoredb]
    # TEMPLATE: uri="esdb://localhost:2113?tls=false"
    user="user"
    password="password"
    host="localhost"
    port="2113"
    tls="false"

    [dns.rabbitmq]
    # TEMPLATE: url="amqp://guest:guest@localhost:5672"
    user="guest"
    password="guest"
    host="localhost"
    port="5672"

[ports]

    [ports.streams]
        meals="StreamMeals"
        health="StreamHealth"

    [ports.queues]
        meals="meals.queue"
        health="meals.health"

    [ports.exchanges]
        meals="meals.exchange"
        health="meals.exchange"


[events]

    [events.meals]
        insert="InsertMealEvent"
        delete="DeleteMealEvent"
        update="UpdateMealEvent"

[logging]
version = 1

    [logging.formatters.formatter]
    format = "[%(asctime)s] [%(levelname)s] [%(filename)s:%(funcName)s:%(lineno)d]: %(message)s"

    [logging.handlers]
    
        [logging.handlers.console]
        class = "logging.StreamHandler"
        level = "DEBUG"
        formatter = "formatter"
        stream = "ext://sys.stderr"

    [logging.root]
    level = "DEBUG"
    handlers = ["console"]

