[dsn]

    [dsn.timescaledb]
    dsn="postgres://user:password@localhost:5433"
    user="user"
    password="password"
    host="localhost"
    port="5433"
    database="meals"

    [dsn.eventstoredb]
    uri="esdb://localhost:2113?tls=false"

    [dsn.redis]
    uri="redis://localhost:6379/0"

    [dsn.rabbitmq]
    url="amqp://guest:guest@127.0.0.1:5672"


[rabbitmq]    
    [rabbitmq.meals]
        queue="meals.queue"
        exchange_name="what_the_health.meals_exchange"
        exchange_type="what_the_health.direct"
            # FANOUT || = "fanout"
            # 
            # TOPIC = "topic"
            # HEADERS = "headers"
            # X_DELAYED_MESSAGE = "x-delayed-message"
            # X_CONSISTENT_HASH = "x-consistent-hash"
            # X_MODULUS_HASH = "x-modulus-hash"

            [rabbitmq.exchanges]
                [rabbitmq.exchanges.]


[subscriptions]

    [subscriptions.meals]
        stream="meals_stream"
        from_end=true

    [subscriptions.health]
        stream="health_stream"
        from_end=true

    [subscriptions.supps]
        stream="supps_stream"
        from_end=true

[events]
    [events.meals]
        insert="MealInsert"

[logging]
version = 1

    [logging.formatters.formatter]
    format = "[%(asctime)s] [%(levelname)s] [%(filename)s:%(funcName)s:%(lineno)d]: %(message)s"

    [logging.handlers]
        [logging.handlers.console]
        class = "logging.StreamHandler"
        level = "DEBUG"
        formatter = "formatter"
        stream = "ext://sys.stderr"

    [logging.root]
    level = "DEBUG"
    handlers = ["console"]
