CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS MEALS;


CREATE TABLE public.meals (
					ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
					TIME TIMESTAMPTZ NOT NULL,
					MEAL_ID UUID NOT NULL,
					USER_ID UUID NOT NULL,
					MEAL_NAME VARCHAR(255) NOT NULL,
					CALORIES DOUBLE PRECISION NOT NULL);


SELECT CREATE_HYPERTABLE('meals', BY_RANGE('time'))