version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    # volumes:
    #   - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
    command: rabbitmq-server

  # rabbitmq-setup:
  #   image: rabbitmq:3-management
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - ./setup_rabbitmq.sh:/setup_rabbitmq.sh
  #   entrypoint: >
  #     sh -c "
  #     sleep 5;
  #     chmod +x /setup_rabbitmq.sh;
  #     /setup_rabbitmq.sh"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale-db
    ports:
      - "5433:5432" # PostgreSQL default port
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - timescale-data:/var/lib/postgresql/data

  eventstoredb:
    image: eventstore/eventstore:latest
    container_name: eventstoredb
    environment:
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
      EVENTSTORE_INT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    ports:
      - "1113:1113"   # External TCP port
      - "2113:2113"   # HTTP port for Admin UI and HTTP API

volumes:
  timescale-data: