[credentials]

[credentials.timescaledb]
# TEMPLATE: dsn="postgres://user:password@localhost:5433/meals" 
user = "user"
password = "password"
host = "localhost"
port = "5433"

[credentials.eventstoredb]
# TEMPLATE: uri="esdb://localhost:2113?tls=false"
user = "user"
password = "password"
host = "localhost"
port = "2113"
tls = "false"

[credentials.rabbitmq]
# TEMPLATE: url="amqp://guest:guest@localhost:5672"
user = "guest"
password = "guest"
host = "localhost"
port = "5672"

[databases]
meals = "meals"
health = "health"

[streams]
meals = "StreamMeals"
health = "StreamHealth"

[queues]
meals = "meals.queue"
health = "meals.health"

[exchanges]
meals = "meals.exchange"
health = "meals.exchange"


[events]
[events.meals]
add = "AddMealEvent"
remove = "RemoveMealEvent"
modify = "ModifyMealEvent"

[logging]
version = 1

[logging.formatters.formatter]
format = "[%(asctime)s] [%(levelname)s] [%(filename)s:%(funcName)s:%(lineno)d]: %(message)s"

[logging.handlers]

[logging.handlers.console]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "formatter"
stream = "ext://sys.stderr"

[logging.root]
level = "DEBUG"
handlers = ["console"]
